# Generated by Django 3.1.13 on 2022-02-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='review',
        ),
    ]
